# Generated by Django 4.1.7 on 2023-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursal',
            fields=[
                ('coursal_id', models.AutoField(primary_key=True, serialize=False)),
                ('coursal_image', models.ImageField(default='', upload_to='coursal_images')),
                ('image_url', models.URLField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
